### ISSUE TITLE
Broken Netherstorm Quests(edit)

### ISSUE THREAD

**Issue by Pharzuph** [Helios-Empire/Helios-Tracker#104]
So, I did all the quests I could find In Netherstorm, and along the way I found few broken quests.

List of the quests:
[[Note: Links are videos related to quests]]
1. [Creatures of the Eco-Domes] [ https://www.youtube.com/watch?v=49rz1YaKmXc ]
2. [Fel Reavers, No Thanks!] [ https://www.youtube.com/watch?v=wvrtr9nOI7U ]
3. [Escape from the Staging Grounds] [ Don't think video is needed ]
4. [A Not-So-Modest Proposal] [ Could not find a proper video showing how quest works ]

Explanation:
1. Using item on mobs(when they are >20% hp) does not affect them. What it should do is put them to sleep.[Does not put them to sleep OR count into quest progress]
2. This is like quest within a quest. What you have to do is collect 5x[Condensed Nether Gas] to complete quest named "Nether Gas In a Fel Fire Engine" which should kill Fel Reaver. Problem is that after doing this quest, game does tell me that Objective is Complete, but progress of [Fel Reavers, No Thanks!] is not updated.
3. After accepting the quest NPC patrols back and forward on 20ft radius never leaving the area.
4. Interacting with the Portal Platform does not summon Image of Wind Trader Marid.

**Comment by dikkedeur** [comment]
1) will propably work on next core restart/reset/update.. its 100% UNTESTED my code.. so yeah who knows.

**Comment by dikkedeur** [comment]
2) will be fixed after next core restart.. the npc will then when item is used be transformed to the correct drained phase hunter so that you can complete quest.. again this is on the fly and not tested :P

**Comment by dikkedeur** [comment]
3) fixed, and tested works now 100%

**Comment by dikkedeur** [comment]
5) needs total rescripting.

**Comment by dikkedeur** [comment]
6) will be fixed after core update/restart/etc

**Comment by dikkedeur** [comment]
in short, since i saw you changed the numbering i will mention here what we have fixed so far.

[It's a Fel Reaver, But with Heart]
[Recharging the Batteries]
[Fel Reavers, No Thanks!]
[A Not-So-Modest Proposal]

**Comment by Pharzuph** [comment]
I removed quests that I was able to finish, however I'm still having problems with [Fel Reavers, No Thanks!] and [A Not-So-Modest Proposal] .

[A Not-So-Modest Proposal] is still stuck on same issue[NPC does not spawn after interacting with Teleport Pad.
[A Not-So-Modest Proposal] after Nether Gas In a Fel Fire Engine is complete it counts into the Quest progress, but I am not able to give in the quest.

**Comment by dikkedeur** [comment]
strange, it might be that something is not working as it should but i cant find out why at this moment..

**Comment by dikkedeur** [comment]
1 creatures of eco domes will work in next core update
